services:
  postgres:
    ports:
      - "127.0.0.1::5432"
  rabbitmq:
    ports: !override
      - "127.0.0.1::5672"
      - "127.0.0.1::15672"
  web:
    ports: !override
      - "127.0.0.1::80"
  api:
    environment:
      TEST_DATABASE_URL: postgresql://commandix_migrator:${MIGRATION_PASSWORD}@postgres:5432/commandix
